### ISSUE TITLE
Updated Tool-Bar Broke Images

### ISSUE THREAD

**Issue by 1069B** [suda/tool-bar-main#19]
When the atom package tool-bar was updated to 1.2.0 it broke all of the different images. I read through all the different issues on the tool-bar repository but felt that a new issue needed to be created over here so the images could be fixed.

**Comment by saschaeggi** [comment]
Same issue here

**Comment by jmrg82** [comment]
+1

**Comment by Musteblume** [comment]
+1

**Comment by jrabadan-ccc** [comment]
Now it's fixed, thanks! 
However, the SAVE icon looks like an ARCHIVE icon... that is weird :S could you please change that?
